url: https://needleworm.github.io/
baseurl: /data

# Site settings
title: BhBan Datasets
email: bhban@kakao.com
description: Datasets by Byunghyun Ban

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/needleworm

# Build settings
highlighter: true
markdown: kramdown
permalink: pretty
